server:
  port: 0
management:
  tracing:
    sampling:
      probability: 1.0

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      database: catalog
      port: 27019

  #esto por si no entendes es para deshabilitar la dependencia de configuracion centralizada en github, tambien lo agregue en los demas yml para q no salte el error
  cloud:
    config:
      enabled: false
  #hasta aca
queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

resilience4j:
  circuitbraker:
    instances:
      movie:
        slidingWindowType: COUNT-BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
      serie:
        slidingWindowType: COUNT-BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movie:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
      serie:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError


