de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
spring:
  data:
    mongodb:
      database: test
      port: 27018
  application:
    name: serie-service
  cloud:
    config:
      enabled: false
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

server:
  port: 0


